### ISSUE TITLE
6.5.0 release included breaking changes

### ISSUE THREAD

**Issue by smoelius** [pyrossh/rust-embed#196]
The following program produces `["main.rs"]` when run with `rust-embed` 6.4.0,\* but `["", "main.rs"]` when run with `rust-embed` 6.5.0:
```rust
use rust_embed::RustEmbed;

#[derive(RustEmbed)]
#[folder = "src"]
struct Asset;

pub fn main() {
    println!("{:?}", Asset::iter().collect::<Vec<_>>());
}
```

`rust-embed` is a valuable tool, so thank you! 🙏 

But I would like to humbly suggest that future changes like this be accompanied by a major version bump.

---

\* You can get the `["main.rs"]` output today if you include the following in your Cargo.toml file:
```toml
[dependencies]
rust-embed = "=6.4.2"
rust-embed-impl = "=6.3.1"
rust-embed-utils = "=7.3.0"
```
